### ISSUE TITLE
Error when using command `npm run testdata`

### ISSUE THREAD

**Issue by Pauan** [sakusimu/mh-skillsimu#1]
I am using Debian, and when I tried to run `npm run testdata`, I got the following error:

```
./tasks/build-testdata.sh: 6: ./tasks/build-testdata.sh: Syntax error: "(" unexpected
```

The `build-testdata.sh` script uses bash-only functionality.

On Debian, `/bin/sh` points to `dash`, not`bash`

I was able to fix this error by changing `#!/bin/sh` to `#!/bin/bash`

**Comment by sakusimu** [comment]
First of all, sorry for late reply.

Thank you for your issue.
I fixed shebang in task scripts.

**Comment by Pauan** [comment]
Thanks!
